# first node will be bootstrap node
- hosts: registry-services[0]
  become: yes
  tasks:

    - name: Create registry data directory
      file:
        path: /var/lib/quobyte/devices/registry-data
        state: directory
        mode: '0755'
    - name: Register pseudo device to hold registry data
      command:
        cmd: /usr/bin/qbootstrap -y -d /var/lib/quobyte/devices/registry-data 
        creates: /var/lib/quobyte/devices/registry-data/QUOBYTE_DEV_SETUP

- hosts: registry-services[1:]
  become: yes
  tasks:
    - name: Create quobyte device directory
      file:
        path: /var/lib/quobyte/devices
        state: directory
        owner: quobyte
        mode: '0755'
    - name: Create registry data directory
      file:
        path: /var/lib/quobyte/devices/registry-data
        state: directory
        owner: quobyte
        mode: '0755'
    - name: Register pseudo device to hold registry data
      command:
        cmd: qmkdev -t REGISTRY -d /var/lib/quobyte/devices/registry-data 
        creates: /var/lib/quobyte/devices/registry-data/QUOBYTE_DEV_SETUP

- hosts: registry-services
  become: yes
  tasks:
    - name: Enable Quobyte core services 
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-registry

- hosts: api-services
  become: yes
  tasks:
    - name: Enable Quobyte core services 
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-api

- hosts: webconsole-services
  become: yes
  tasks:
    - name: Enable Quobyte core services 
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-webconsole
