- hosts: cluster
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: Add Quobyte repository signing key
      apt_key:
        url: https://packages.quobyte.com/repo/v3/apt/pubkey.gpg 
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Add Quobyte apt repository to sources list
      apt_repository:
        repo: deb https://packages.quobyte.com/repo/v3/apt buster main
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Add Quobyte rpm repository to sources list
      yum_repository:
        name: quobyte
        description: Quobyte rpm repo
        baseurl: https://packages.quobyte.com/repo/v3/rpm/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}
        gpgkey: https://packages.quobyte.com/repo/v3/apt/pubkey.gpg
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Install Debian packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - default-jre-headless
        - quobyte-thirdparty-libraries=2:3.0~pre8.1
        - quobyte-server=2:3.0~pre8.1
        - xfsprogs
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
    - name: Install RPM packages
      yum: 
        update_cache: yes
        allow_downgrade: yes
        state: present
        name: "{{ packages }}"
      vars:
        packages:
        - java-11-openjdk 
        - quobyte-thirdparty-libraries-3.0~pre8.1
        - quobyte-server-3.0~pre8.1
        - xfsprogs
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Write /etc/quobyte/host.cfg
      template:
        src: templates/host.cfg.jinja2
        dest: "/etc/quobyte/host.cfg"

# first node will be bootstrap node
- hosts: cluster[0]
  become: yes
  tasks:

    - name: Create registry data directory
      file:
        path: /var/lib/quobyte/devices/registry-data
        state: directory
        mode: '0755'
    - name: Register pseudo device to hold registry data
      command:
        #cmd: qmkdev -t REGISTRY -d /var/lib/quobyte/devices/registry-data 
        #creates: /var/lib/quobyte/devices/registry-data/QUOBYTE_DEV_SETUP
        cmd: /usr/bin/qbootstrap -y /var/lib/quobyte/registry-data 
        creates: /var/lib/quobyte/registry-data/QUOBYTE_DEV_SETUP

#    - name: Create a xfs filesystem on /dev/sdb
#      filesystem:
#        fstype: xfs 
#        dev: /dev/sdb
#    - name: Label registry device with "quobyte-dev" 
#      command:
#        cmd: xfs_admin -L quobyte-dev /dev/sdb 
#        creates: /var/lib/quobyte/registry-data/QUOBYTE_DEV_SETUP
#    - name: Create registry mount path
#      file:
#        path: /var/lib/quobyte/registry-data
#        state: directory
#        mode: '0755'
#    - name: Mount registry device
#      mount:
#        path: /var/lib/quobyte/registry-data
#        src: /dev/sdb
#        fstype: xfs 
#        state: mounted
#    - name: Run qmkdev to create registry device 
#      command:
#        cmd: /usr/bin/qbootstrap -y /var/lib/quobyte/registry-data 
#        creates: /var/lib/quobyte/registry-data/QUOBYTE_DEV_SETUP
#
- hosts: cluster[1:3]
  become: yes
  tasks:
    - name: Create quobyte device directory
      file:
        path: /var/lib/quobyte/devices
        state: directory
        owner: quobyte
        mode: '0755'
    - name: Create registry data directory
      file:
        path: /var/lib/quobyte/devices/registry-data
        state: directory
        owner: quobyte
        mode: '0755'
    - name: Register pseudo device to hold registry data
      command:
        cmd: qmkdev -t REGISTRY -d /var/lib/quobyte/devices/registry-data 
        creates: /var/lib/quobyte/devices/registry-data/QUOBYTE_DEV_SETUP
        #cmd: /usr/bin/qbootstrap -y /var/lib/quobyte/registry-data 
        #creates: /var/lib/quobyte/registry-data/QUOBYTE_DEV_SETUP

#    - name: Create a xfs filesystem on /dev/sdb
#      filesystem:
#        fstype: xfs 
#        dev: /dev/sdb
#    - name: Label registry device with "quobyte-dev" 
#      command:
#        cmd: xfs_admin -L quobyte-dev /dev/sdb 
#        creates: /var/lib/quobyte/registry-data/QUOBYTE_DEV_SETUP
#    - name: Create registry mount path
#      file:
#        path: /var/lib/quobyte/registry-data
#        state: directory
#        mode: '0755'
#    - name: Mount registry device
#      mount:
#        path: /var/lib/quobyte/registry-data
#        src: /dev/sdb
#        fstype: xfs 
#        state: mounted
#    - name: Run qmkdev to create registry device 
#      command:
#        cmd: /usr/bin/qmkdev -t REGISTRY /var/lib/quobyte/registry-data 
#        creates: /var/lib/quobyte/registry-data/QUOBYTE_DEV_SETUP
#
- hosts: cluster
  become: yes
  tasks:
    - name: Enable Quobyte core services 
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-registry
         - quobyte-api
         - quobyte-webconsole
         - quobyte-data
         - quobyte-metadata

