# first node will be bootstrap node
- hosts: registry-services[0]
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:

    - name: Create registry data directory
      file:
        path: /var/lib/quobyte/devices/registry-data
        state: directory
        mode: '0755'
    - name: Register pseudo device to hold registry data
      command:
        cmd: /usr/bin/qbootstrap -y -d /var/lib/quobyte/devices/registry-data 
        creates: /var/lib/quobyte/devices/registry-data/QUOBYTE_DEV_SETUP

    - name: Enable Quobyte core services 
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-registry
         - quobyte-api

    - name: Wait for API RPC port to become available 
      wait_for:
        port: 7865 
        delay: 2

    - name: Wait for API metrics port to become available 
      wait_for:
        port: 7875 
        delay: 2

    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: export systemconfig 
      shell:
        cmd: qmgmt -u {{ api_service }} systemconfig export /tmp/systemconfig

    - name: Register systemconfig
      shell: 
        cmd: cat /tmp/systemconfig
      register: systemconfig

    - name: add clustername to systemconfig
      blockinfile:
        path: /tmp/systemconfig
        block: |
          cluster_configuration {
            cluster_name: "{{ clustername }}"
          }
      when: repo_id is not defined 

    - name: Add service networks to systemconfig
      blockinfile:
        path: /tmp/systemconfig
        block: |
          network {
            enabled_service_networks: "{{ network }}"
            enabled_client_networks: "{{ network }}"
          }
      when: '"enabled_service_networks" not in systemconfig.stdout' 

    - name: Import system configuration
      shell:
        cmd: /usr/bin/qmgmt -u {{ api_service }} systemconfig import /tmp/systemconfig
      tags: system

    - name: Restart Quobyte registry services 
      service:
        state: restarted
        name: quobyte-registry 

- hosts: registry-services[1:]
  become: yes
  tasks:
    - name: Create quobyte device directory
      file:
        path: /var/lib/quobyte/devices
        state: directory
        owner: quobyte
        mode: '0755'
    - name: Create registry data directory
      file:
        path: /var/lib/quobyte/devices/registry-data
        state: directory
        owner: quobyte
        mode: '0755'
    - name: Register pseudo device to hold registry data
      command:
        cmd: qmkdev -t REGISTRY -d /var/lib/quobyte/devices/registry-data 
        creates: /var/lib/quobyte/devices/registry-data/QUOBYTE_DEV_SETUP

- hosts: registry-services
  become: yes
  tasks:
    - name: Enable Quobyte core services 
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-registry

- hosts: api-services
  become: yes
  tasks:
    - name: Enable Quobyte core services 
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-api

- hosts: webconsole-services
  become: yes
  tasks:
    - name: Enable Quobyte core services 
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-webconsole

