- hosts: registry-services[0] 
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:

    - name: Create Quobyte Super User
      shell:
        cmd: qmgmt -u {{ api_service }} user config add {{ admin_user }} {{ admin_email | default('changeme@myorga.org') }} SUPER_USER password {{ admin_password }}
 
