- hosts: quobyte-server 
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: Install tuned Debian package 
      apt: 
        name: tuned
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install tuned RPM package 
      yum: 
        name: tuned
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


    - name: Set Quobyte tuned server profile
      shell:
        cmd: tuned-adm profile quobyte-server-performance

    - name: Restart tuned
      service:
        name: tuned
        state: restarted
        enabled: yes

- hosts: registry-services 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte registry services 
      service:
        state: restarted
        name: quobyte-registry 
- hosts: api-services 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte api services 
      service:
        state: restarted
        name: quobyte-api 
- hosts: webconsole-services 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte webconsole services 
      service:
        state: restarted
        name: quobyte-webconsole 
- hosts: webconsole-services 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte registry services 
      service:
        state: restarted
        name: quobyte-registry 
- hosts: metadata-services 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte metadata services 
      service:
        state: restarted
        name: quobyte-metadata 
- hosts: data-services 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte data services 
      service:
        state: restarted
        name: quobyte-data 
- hosts: s3-services 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte s3 services 
      service:
        state: restarted
        name: quobyte-s3 
- hosts: nfs-services 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte nfs services 
      service:
        state: restarted
        name: quobyte-nfs 
